/*
 * HealthKit constants
 */

public struct HMConstants
{
    public static let sharedInstance = HMConstants()

    // Default values if unavailable in user profile.
    public let defaultToMetricUnits = NSLocale.currentLocale().objectForKey(NSLocaleUsesMetricSystem)!.boolValue

    // Metadata key for generated samples.
    public let generatedSampleKey : String = "MCLGen"
    public let generatedUploadSampleKey : String = "MCUGen"

    public let healthKitTypesWithCustomMetrics: Set<String> = [
        HKQuantityTypeIdentifierBodyMass,
        HKQuantityTypeIdentifierHeight,
        HKQuantityTypeIdentifierLeanBodyMass
    ]

    // Note: these are in alphabetical order within each type.
    public let healthKitTypesToRead : Set<HKObjectType>? = [
        HKObjectType.categoryTypeForIdentifier(HKCategoryTypeIdentifierSleepAnalysis)!,
        HKObjectType.categoryTypeForIdentifier(HKCategoryTypeIdentifierAppleStandHour)!,
        HKObjectType.characteristicTypeForIdentifier(HKCharacteristicTypeIdentifierBloodType)!,
        HKObjectType.characteristicTypeForIdentifier(HKCharacteristicTypeIdentifierBiologicalSex)!,
        HKObjectType.characteristicTypeForIdentifier(HKCharacteristicTypeIdentifierFitzpatrickSkinType)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierActiveEnergyBurned)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBasalBodyTemperature)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBasalEnergyBurned)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodAlcoholContent)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodGlucose)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodPressureDiastolic)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodPressureSystolic)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyFatPercentage)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyMass)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyMassIndex)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyTemperature)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryBiotin)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCaffeine)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCalcium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCarbohydrates)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCholesterol)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryChloride)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryChromium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCopper)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryEnergyConsumed)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatMonounsaturated)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatPolyunsaturated)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatSaturated)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatTotal)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFiber)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFolate)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryIodine)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryIron)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryMagnesium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryManganese)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryMolybdenum)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryNiacin)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPantothenicAcid)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPhosphorus)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPotassium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryProtein)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryRiboflavin)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySelenium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySodium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySugar)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryThiamin)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminA)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminB12)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminB6)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminC)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminD)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminE)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminK)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryWater)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryZinc)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDistanceWalkingRunning)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierElectrodermalActivity)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierFlightsClimbed)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierForcedExpiratoryVolume1)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierForcedVitalCapacity)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierHeartRate)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierHeight)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierInhalerUsage)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierLeanBodyMass)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierNikeFuel)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierNumberOfTimesFallen)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierOxygenSaturation)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierPeakExpiratoryFlowRate)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierPeripheralPerfusionIndex)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierRespiratoryRate)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierStepCount)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierUVExposure)!,
        HKObjectType.workoutType()
    ]

    public let healthKitTypesToWrite : Set<HKSampleType>? =
        Deployment.sharedInstance.withDebugView ?
            // Cannot write apple stand hour, nike fuel.
            [
                HKObjectType.categoryTypeForIdentifier(HKCategoryTypeIdentifierSleepAnalysis)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierActiveEnergyBurned)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBasalBodyTemperature)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBasalEnergyBurned)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodAlcoholContent)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodGlucose)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodPressureDiastolic)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodPressureSystolic)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyFatPercentage)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyMass)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyMassIndex)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyTemperature)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryBiotin)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCalcium)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCaffeine)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCarbohydrates)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCholesterol)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryChloride)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryChromium)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCopper)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryEnergyConsumed)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatMonounsaturated)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatPolyunsaturated)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatSaturated)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatTotal)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFiber)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFolate)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryIodine)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryIron)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryMagnesium)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryManganese)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryMolybdenum)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryNiacin)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPantothenicAcid)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPhosphorus)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPotassium)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryProtein)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryRiboflavin)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySelenium)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySodium)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySugar)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryThiamin)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminA)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminB12)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminB6)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminC)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminD)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminE)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminK)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryWater)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryZinc)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDistanceWalkingRunning)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierElectrodermalActivity)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierFlightsClimbed)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierForcedExpiratoryVolume1)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierForcedVitalCapacity)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierHeartRate)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierHeight)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierInhalerUsage)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierLeanBodyMass)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierNumberOfTimesFallen)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierOxygenSaturation)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierPeakExpiratoryFlowRate)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierPeripheralPerfusionIndex)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierRespiratoryRate)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierStepCount)!,
                HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierUVExposure)!,
                HKObjectType.workoutType()
            ]
            :
            [
                HKObjectType.categoryTypeForIdentifier(HKCategoryTypeIdentifierSleepAnalysis)!,
                HKQuantityType.workoutType()
            ]

    // Note: these are in alphabetical order within each type.
    public let healthKitTypesToObserve : [HKSampleType] = [
        HKObjectType.categoryTypeForIdentifier(HKCategoryTypeIdentifierSleepAnalysis)!,
        HKObjectType.categoryTypeForIdentifier(HKCategoryTypeIdentifierAppleStandHour)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierActiveEnergyBurned)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBasalBodyTemperature)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBasalEnergyBurned)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodAlcoholContent)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodGlucose)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodPressureDiastolic)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBloodPressureSystolic)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyFatPercentage)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyMass)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyMassIndex)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierBodyTemperature)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryBiotin)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCalcium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCaffeine)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCarbohydrates)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCholesterol)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryChloride)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryChromium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryCopper)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryEnergyConsumed)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatMonounsaturated)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatPolyunsaturated)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatSaturated)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFatTotal)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFiber)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryFolate)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryIodine)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryIron)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryMagnesium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryManganese)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryMolybdenum)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryNiacin)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPantothenicAcid)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPhosphorus)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryPotassium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryProtein)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryRiboflavin)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySelenium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySodium)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietarySugar)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryThiamin)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminA)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminB12)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminB6)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminC)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminD)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminE)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryVitaminK)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryWater)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDietaryZinc)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierDistanceWalkingRunning)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierElectrodermalActivity)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierFlightsClimbed)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierForcedExpiratoryVolume1)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierForcedVitalCapacity)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierHeartRate)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierHeight)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierInhalerUsage)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierLeanBodyMass)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierNikeFuel)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierNumberOfTimesFallen)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierOxygenSaturation)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierPeakExpiratoryFlowRate)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierPeripheralPerfusionIndex)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierRespiratoryRate)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierStepCount)!,
        HKObjectType.quantityTypeForIdentifier(HKQuantityTypeIdentifierUVExposure)!,
        HKObjectType.workoutType()
    ]

    // Note: these are in alphabetical order within each type.
    public let healthKitShortNames : [String: String] = [
        HKCategoryTypeIdentifierAppleStandHour            : "Stood",
        HKCategoryTypeIdentifierSleepAnalysis             : "Sleep",
        HKCharacteristicTypeIdentifierBloodType           : "Blood type",
        HKCharacteristicTypeIdentifierBiologicalSex       : "Sex",
        HKCharacteristicTypeIdentifierFitzpatrickSkinType : "Skin type",
        HKCorrelationTypeIdentifierBloodPressure          : "BP",
        HKQuantityTypeIdentifierActiveEnergyBurned        : "Cal burned",
        HKQuantityTypeIdentifierBasalBodyTemperature      : "Temperature(B)",
        HKQuantityTypeIdentifierBasalEnergyBurned         : "Cal burned(B)",
        HKQuantityTypeIdentifierBloodAlcoholContent       : "BAC",
        HKQuantityTypeIdentifierBloodGlucose              : "Glucose",
        HKQuantityTypeIdentifierBloodPressureDiastolic    : "BP Diastolic",
        HKQuantityTypeIdentifierBloodPressureSystolic     : "BP Systolic",
        HKQuantityTypeIdentifierBodyFatPercentage         : "Body Fat",
        HKQuantityTypeIdentifierBodyMass                  : "Weight",
        HKQuantityTypeIdentifierBodyMassIndex             : "BMI",
        HKQuantityTypeIdentifierBodyTemperature           : "Temperature",
        HKQuantityTypeIdentifierDietaryBiotin             : "Biotin",
        HKQuantityTypeIdentifierDietaryCalcium            : "Calcium",
        HKQuantityTypeIdentifierDietaryCaffeine           : "Caffeine",
        HKQuantityTypeIdentifierDietaryCarbohydrates      : "Carbs",
        HKQuantityTypeIdentifierDietaryCholesterol        : "Cholesterol",
        HKQuantityTypeIdentifierDietaryChloride           : "Chloride",
        HKQuantityTypeIdentifierDietaryChromium           : "Chromium",
        HKQuantityTypeIdentifierDietaryCopper             : "Copper",
        HKQuantityTypeIdentifierDietaryEnergyConsumed     : "Net Calories",
        HKQuantityTypeIdentifierDietaryFatMonounsaturated : "Fat(MS)",
        HKQuantityTypeIdentifierDietaryFatPolyunsaturated : "Fat(PS)",
        HKQuantityTypeIdentifierDietaryFatSaturated       : "Fat(S)",
        HKQuantityTypeIdentifierDietaryFatTotal           : "Fat",
        HKQuantityTypeIdentifierDietaryFiber              : "Fiber",
        HKQuantityTypeIdentifierDietaryFolate             : "Folate",
        HKQuantityTypeIdentifierDietaryIodine             : "Iodine",
        HKQuantityTypeIdentifierDietaryIron               : "Iron",
        HKQuantityTypeIdentifierDietaryMagnesium          : "Magnesium",
        HKQuantityTypeIdentifierDietaryManganese          : "Manganese",
        HKQuantityTypeIdentifierDietaryMolybdenum         : "Molybdenum",
        HKQuantityTypeIdentifierDietaryNiacin             : "Niacin",
        HKQuantityTypeIdentifierDietaryPantothenicAcid    : "Pant. Acid",
        HKQuantityTypeIdentifierDietaryPhosphorus         : "Phosphorus",
        HKQuantityTypeIdentifierDietaryPotassium          : "Potassium",
        HKQuantityTypeIdentifierDietaryProtein            : "Protein",
        HKQuantityTypeIdentifierDietaryRiboflavin         : "Riboflavin",
        HKQuantityTypeIdentifierDietarySelenium           : "Selenium",
        HKQuantityTypeIdentifierDietarySodium             : "Salt",
        HKQuantityTypeIdentifierDietarySugar              : "Sugar",
        HKQuantityTypeIdentifierDietaryThiamin            : "Thiamin",
        HKQuantityTypeIdentifierDietaryVitaminA           : "Vit. A",
        HKQuantityTypeIdentifierDietaryVitaminB12         : "Vit. B12",
        HKQuantityTypeIdentifierDietaryVitaminB6          : "Vit. B6",
        HKQuantityTypeIdentifierDietaryVitaminC           : "Vit. C",
        HKQuantityTypeIdentifierDietaryVitaminD           : "Vit. D",
        HKQuantityTypeIdentifierDietaryVitaminE           : "Vit. E",
        HKQuantityTypeIdentifierDietaryVitaminK           : "Vit. K",
        HKQuantityTypeIdentifierDietaryWater              : "Water",
        HKQuantityTypeIdentifierDietaryZinc               : "Zinc",
        HKQuantityTypeIdentifierDistanceWalkingRunning    : "Distance",
        HKQuantityTypeIdentifierElectrodermalActivity     : "Electrodermal",
        HKQuantityTypeIdentifierFlightsClimbed            : "Climbed",
        HKQuantityTypeIdentifierForcedExpiratoryVolume1   : "Exp. Volume",
        HKQuantityTypeIdentifierForcedVitalCapacity       : "Vital Capacity",
        HKQuantityTypeIdentifierHeartRate                 : "Heart rate",
        HKQuantityTypeIdentifierHeight                    : "Height",
        HKQuantityTypeIdentifierInhalerUsage              : "Inhaler",
        HKQuantityTypeIdentifierLeanBodyMass              : "Lean Weight",
        HKQuantityTypeIdentifierNikeFuel                  : "Nike Fuel",
        HKQuantityTypeIdentifierNumberOfTimesFallen       : "Fallen",
        HKQuantityTypeIdentifierOxygenSaturation          : "Oxygen",
        HKQuantityTypeIdentifierPeakExpiratoryFlowRate    : "Exp. Flow",
        HKQuantityTypeIdentifierPeripheralPerfusionIndex  : "Perfusion",
        HKQuantityTypeIdentifierRespiratoryRate           : "Respiratory",
        HKQuantityTypeIdentifierStepCount                 : "Steps",
        HKQuantityTypeIdentifierUVExposure                : "Light",
        HKObjectType.workoutType().identifier             : "Workouts/Meals"
    ]

    // Note: We use strings as short ids to be compatible with JSON dictionary keys.
    public let healthKitShortIds : [String: String] = [
        HKCategoryTypeIdentifierSleepAnalysis             : "0",
        HKCategoryTypeIdentifierAppleStandHour            : "1",
        HKQuantityTypeIdentifierActiveEnergyBurned        : "2",
        HKQuantityTypeIdentifierBasalBodyTemperature      : "3",
        HKQuantityTypeIdentifierBasalEnergyBurned         : "4",
        HKQuantityTypeIdentifierBloodAlcoholContent       : "5",
        HKQuantityTypeIdentifierBloodGlucose              : "6",
        HKQuantityTypeIdentifierBloodPressureDiastolic    : "7",
        HKQuantityTypeIdentifierBloodPressureSystolic     : "8",
        HKQuantityTypeIdentifierBodyFatPercentage         : "9",
        HKQuantityTypeIdentifierBodyMass                  : "10",
        HKQuantityTypeIdentifierBodyMassIndex             : "11",
        HKQuantityTypeIdentifierBodyTemperature           : "12",
        HKQuantityTypeIdentifierDietaryBiotin             : "13",
        HKQuantityTypeIdentifierDietaryCalcium            : "14",
        HKQuantityTypeIdentifierDietaryCaffeine           : "15",
        HKQuantityTypeIdentifierDietaryCarbohydrates      : "16",
        HKQuantityTypeIdentifierDietaryCholesterol        : "17",
        HKQuantityTypeIdentifierDietaryChloride           : "18",
        HKQuantityTypeIdentifierDietaryChromium           : "19",
        HKQuantityTypeIdentifierDietaryCopper             : "20",
        HKQuantityTypeIdentifierDietaryEnergyConsumed     : "21",
        HKQuantityTypeIdentifierDietaryFatMonounsaturated : "22",
        HKQuantityTypeIdentifierDietaryFatPolyunsaturated : "23",
        HKQuantityTypeIdentifierDietaryFatSaturated       : "24",
        HKQuantityTypeIdentifierDietaryFatTotal           : "25",
        HKQuantityTypeIdentifierDietaryFiber              : "26",
        HKQuantityTypeIdentifierDietaryFolate             : "27",
        HKQuantityTypeIdentifierDietaryIodine             : "28",
        HKQuantityTypeIdentifierDietaryIron               : "29",
        HKQuantityTypeIdentifierDietaryMagnesium          : "30",
        HKQuantityTypeIdentifierDietaryManganese          : "31",
        HKQuantityTypeIdentifierDietaryMolybdenum         : "32",
        HKQuantityTypeIdentifierDietaryNiacin             : "33",
        HKQuantityTypeIdentifierDietaryPantothenicAcid    : "34",
        HKQuantityTypeIdentifierDietaryPhosphorus         : "35",
        HKQuantityTypeIdentifierDietaryPotassium          : "36",
        HKQuantityTypeIdentifierDietaryProtein            : "37",
        HKQuantityTypeIdentifierDietaryRiboflavin         : "38",
        HKQuantityTypeIdentifierDietarySelenium           : "39",
        HKQuantityTypeIdentifierDietarySodium             : "40",
        HKQuantityTypeIdentifierDietarySugar              : "41",
        HKQuantityTypeIdentifierDietaryThiamin            : "42",
        HKQuantityTypeIdentifierDietaryVitaminA           : "43",
        HKQuantityTypeIdentifierDietaryVitaminB12         : "44",
        HKQuantityTypeIdentifierDietaryVitaminB6          : "45",
        HKQuantityTypeIdentifierDietaryVitaminC           : "46",
        HKQuantityTypeIdentifierDietaryVitaminD           : "47",
        HKQuantityTypeIdentifierDietaryVitaminE           : "48",
        HKQuantityTypeIdentifierDietaryVitaminK           : "49",
        HKQuantityTypeIdentifierDietaryWater              : "50",
        HKQuantityTypeIdentifierDietaryZinc               : "51",
        HKQuantityTypeIdentifierDistanceWalkingRunning    : "52",
        HKQuantityTypeIdentifierElectrodermalActivity     : "53",
        HKQuantityTypeIdentifierFlightsClimbed            : "54",
        HKQuantityTypeIdentifierForcedExpiratoryVolume1   : "55",
        HKQuantityTypeIdentifierForcedVitalCapacity       : "56",
        HKQuantityTypeIdentifierHeartRate                 : "57",
        HKQuantityTypeIdentifierHeight                    : "58",
        HKQuantityTypeIdentifierInhalerUsage              : "59",
        HKQuantityTypeIdentifierLeanBodyMass              : "60",
        HKQuantityTypeIdentifierNikeFuel                  : "61",
        HKQuantityTypeIdentifierNumberOfTimesFallen       : "62",
        HKQuantityTypeIdentifierOxygenSaturation          : "63",
        HKQuantityTypeIdentifierPeakExpiratoryFlowRate    : "64",
        HKQuantityTypeIdentifierPeripheralPerfusionIndex  : "65",
        HKQuantityTypeIdentifierRespiratoryRate           : "66",
        HKQuantityTypeIdentifierStepCount                 : "67",
        HKQuantityTypeIdentifierUVExposure                : "68",
        HKObjectType.workoutType().identifier             : "69",
    ]

    // A mapping between HealthKit types and MC database schema attributes.
    //
    // TODO: the following types have a more complex mapping.
    // HKCorrelationTypeIdentifierBloodPressure          : "BP",            // Maps to individual components.
    //
    // TODO: the following types should be stored as profile attribute:
    // HKCharacteristicTypeIdentifierBloodType           : "Blood type",
    // HKCharacteristicTypeIdentifierBiologicalSex       : "Sex",
    // HKCharacteristicTypeIdentifierFitzpatrickSkinType : "Skin type",
    //

    // MCDB columns that are categorized types.
    public let mcdbCategorized: Set<String>  = ["meal_duration", "activity_duration", "activity_value"]

    // HealthKit quantity types that should query activity values subcomponents.
    public let hkQuantityToMCDBActivity : [String: (String, String)] = [
        HKQuantityTypeIdentifierDistanceWalkingRunning    : ("distance_walking_running", "distance"),
        HKQuantityTypeIdentifierFlightsClimbed            : ("flights_climbed", "flights"),
        HKQuantityTypeIdentifierStepCount                 : ("step_count", "step_count")
    ]

    // MCDB categorized values that should convert into HealthKit quantities.
    // This should be the inverse of the hkQuantityToMCDBActivity mapping.
    public let mcdbActivityToHKQuantity: [String: (String, String)] = [
        "distance_walking_running" : ("distance",   HKQuantityTypeIdentifierDistanceWalkingRunning),
        "flights_climbed"          : ("flights",    HKQuantityTypeIdentifierFlightsClimbed),
        "step_count"               : ("step_count", HKQuantityTypeIdentifierStepCount)
    ]

    public let hkToMCDB : [String: String] = [
        HKCategoryTypeIdentifierAppleStandHour            : "apple_stand_hour",
        HKCategoryTypeIdentifierSleepAnalysis             : "sleep_duration",
        HKQuantityTypeIdentifierActiveEnergyBurned        : "active_energy_burned",
        HKQuantityTypeIdentifierBasalBodyTemperature      : "basal_body_temperature",
        HKQuantityTypeIdentifierBasalEnergyBurned         : "basal_energy_burned",
        HKQuantityTypeIdentifierBloodAlcoholContent       : "blood_alcohol_content",
        HKQuantityTypeIdentifierBloodGlucose              : "blood_glucose",
        HKQuantityTypeIdentifierBloodPressureDiastolic    : "diastolic_blood_pressure",
        HKQuantityTypeIdentifierBloodPressureSystolic     : "systolic_blood_pressure",
        HKQuantityTypeIdentifierBodyFatPercentage         : "body_fat_percentage",
        HKQuantityTypeIdentifierBodyMass                  : "body_weight",
        HKQuantityTypeIdentifierBodyMassIndex             : "body_mass_index",
        HKQuantityTypeIdentifierBodyTemperature           : "body_temperature",
        HKQuantityTypeIdentifierDietaryBiotin             : "dietary_biotin",
        HKQuantityTypeIdentifierDietaryCalcium            : "dietary_calcium",
        HKQuantityTypeIdentifierDietaryCaffeine           : "dietary_caffeine",
        HKQuantityTypeIdentifierDietaryCarbohydrates      : "dietary_carbohydrates",
        HKQuantityTypeIdentifierDietaryCholesterol        : "dietary_cholesterol",
        HKQuantityTypeIdentifierDietaryChloride           : "dietary_chloride",
        HKQuantityTypeIdentifierDietaryChromium           : "dietary_chromium",
        HKQuantityTypeIdentifierDietaryCopper             : "dietary_copper",
        HKQuantityTypeIdentifierDietaryEnergyConsumed     : "dietary_energy_consumed",
        HKQuantityTypeIdentifierDietaryFatMonounsaturated : "dietary_fat_monounsaturated",
        HKQuantityTypeIdentifierDietaryFatPolyunsaturated : "dietary_fat_polyunsaturated",
        HKQuantityTypeIdentifierDietaryFatSaturated       : "dietary_fat_saturated",
        HKQuantityTypeIdentifierDietaryFatTotal           : "dietary_fat_total",
        HKQuantityTypeIdentifierDietaryFiber              : "dietary_fiber",
        HKQuantityTypeIdentifierDietaryFolate             : "dietary_folate",
        HKQuantityTypeIdentifierDietaryIodine             : "dietary_iodine",
        HKQuantityTypeIdentifierDietaryIron               : "dietary_iron",
        HKQuantityTypeIdentifierDietaryMagnesium          : "dietary_magnesium",
        HKQuantityTypeIdentifierDietaryManganese          : "dietary_manganese",
        HKQuantityTypeIdentifierDietaryMolybdenum         : "dietary_molybdenum",
        HKQuantityTypeIdentifierDietaryNiacin             : "dietary_niacin",
        HKQuantityTypeIdentifierDietaryPantothenicAcid    : "dietary_pantothenic_acid",
        HKQuantityTypeIdentifierDietaryPhosphorus         : "dietary_phosphorus",
        HKQuantityTypeIdentifierDietaryPotassium          : "dietary_potassium",
        HKQuantityTypeIdentifierDietaryProtein            : "dietary_protein",
        HKQuantityTypeIdentifierDietaryRiboflavin         : "dietary_riboflavin",
        HKQuantityTypeIdentifierDietarySelenium           : "dietary_selenium",
        HKQuantityTypeIdentifierDietarySodium             : "dietary_sodium",
        HKQuantityTypeIdentifierDietarySugar              : "dietary_sugar",
        HKQuantityTypeIdentifierDietaryThiamin            : "dietary_thiamin",
        HKQuantityTypeIdentifierDietaryVitaminA           : "dietary_vitamina",
        HKQuantityTypeIdentifierDietaryVitaminB12         : "dietary_vitaminb12",
        HKQuantityTypeIdentifierDietaryVitaminB6          : "dietary_vitaminb6",
        HKQuantityTypeIdentifierDietaryVitaminC           : "dietary_vitaminc",
        HKQuantityTypeIdentifierDietaryVitaminD           : "dietary_vitamind",
        HKQuantityTypeIdentifierDietaryVitaminE           : "dietary_vitamine",
        HKQuantityTypeIdentifierDietaryVitaminK           : "dietary_vitamink",
        HKQuantityTypeIdentifierDietaryWater              : "dietary_water",
        HKQuantityTypeIdentifierDietaryZinc               : "dietary_zinc",
        HKQuantityTypeIdentifierElectrodermalActivity     : "electrodermal_activity",
        HKQuantityTypeIdentifierForcedExpiratoryVolume1   : "forced_expiratory_volume_one_second",
        HKQuantityTypeIdentifierForcedVitalCapacity       : "forced_vital_capacity",
        HKQuantityTypeIdentifierHeartRate                 : "heart_rate",
        HKQuantityTypeIdentifierHeight                    : "body_height",
        HKQuantityTypeIdentifierInhalerUsage              : "inhaler_usage",
        HKQuantityTypeIdentifierLeanBodyMass              : "lean_body_mass",
        HKQuantityTypeIdentifierNikeFuel                  : "nike_fuel",
        HKQuantityTypeIdentifierNumberOfTimesFallen       : "number_of_times_fallen",
        HKQuantityTypeIdentifierOxygenSaturation          : "blood_oxygen_saturation",
        HKQuantityTypeIdentifierPeakExpiratoryFlowRate    : "peak_expiratory_flow",
        HKQuantityTypeIdentifierPeripheralPerfusionIndex  : "peripheral_perfusion_index",
        HKQuantityTypeIdentifierRespiratoryRate           : "respiratory_rate",
        HKQuantityTypeIdentifierUVExposure                : "uv_exposure"
    ]

    public let mcdbToHK : [String: String] = [
        "apple_stand_hour"                    : HKCategoryTypeIdentifierAppleStandHour            ,
        "sleep_duration"                      : HKCategoryTypeIdentifierSleepAnalysis             ,
        "active_energy_burned"                : HKQuantityTypeIdentifierActiveEnergyBurned        ,
        "basal_body_temperature"              : HKQuantityTypeIdentifierBasalBodyTemperature      ,
        "basal_energy_burned"                 : HKQuantityTypeIdentifierBasalEnergyBurned         ,
        "blood_alcohol_content"               : HKQuantityTypeIdentifierBloodAlcoholContent       ,
        "blood_glucose"                       : HKQuantityTypeIdentifierBloodGlucose              ,
        "diastolic_blood_pressure"            : HKQuantityTypeIdentifierBloodPressureDiastolic    ,
        "systolic_blood_pressure"             : HKQuantityTypeIdentifierBloodPressureSystolic     ,
        "body_fat_percentage"                 : HKQuantityTypeIdentifierBodyFatPercentage         ,
        "body_weight"                         : HKQuantityTypeIdentifierBodyMass                  ,
        "body_mass_index"                     : HKQuantityTypeIdentifierBodyMassIndex             ,
        "body_temperature"                    : HKQuantityTypeIdentifierBodyTemperature           ,
        "dietary_biotin"                      : HKQuantityTypeIdentifierDietaryBiotin             ,
        "dietary_calcium"                     : HKQuantityTypeIdentifierDietaryCalcium            ,
        "dietary_caffeine"                    : HKQuantityTypeIdentifierDietaryCaffeine           ,
        "dietary_carbohydrates"               : HKQuantityTypeIdentifierDietaryCarbohydrates      ,
        "dietary_cholesterol"                 : HKQuantityTypeIdentifierDietaryCholesterol        ,
        "dietary_chloride"                    : HKQuantityTypeIdentifierDietaryChloride           ,
        "dietary_chromium"                    : HKQuantityTypeIdentifierDietaryChromium           ,
        "dietary_copper"                      : HKQuantityTypeIdentifierDietaryCopper             ,
        "dietary_energy_consumed"             : HKQuantityTypeIdentifierDietaryEnergyConsumed     ,
        "dietary_fat_monounsaturated"         : HKQuantityTypeIdentifierDietaryFatMonounsaturated ,
        "dietary_fat_polyunsaturated"         : HKQuantityTypeIdentifierDietaryFatPolyunsaturated ,
        "dietary_fat_saturated"               : HKQuantityTypeIdentifierDietaryFatSaturated       ,
        "dietary_fat_total"                   : HKQuantityTypeIdentifierDietaryFatTotal           ,
        "dietary_fiber"                       : HKQuantityTypeIdentifierDietaryFiber              ,
        "dietary_folate"                      : HKQuantityTypeIdentifierDietaryFolate             ,
        "dietary_iodine"                      : HKQuantityTypeIdentifierDietaryIodine             ,
        "dietary_iron"                        : HKQuantityTypeIdentifierDietaryIron               ,
        "dietary_magnesium"                   : HKQuantityTypeIdentifierDietaryMagnesium          ,
        "dietary_manganese"                   : HKQuantityTypeIdentifierDietaryManganese          ,
        "dietary_molybdenum"                  : HKQuantityTypeIdentifierDietaryMolybdenum         ,
        "dietary_niacin"                      : HKQuantityTypeIdentifierDietaryNiacin             ,
        "dietary_pantothenic_acid"            : HKQuantityTypeIdentifierDietaryPantothenicAcid    ,
        "dietary_phosphorus"                  : HKQuantityTypeIdentifierDietaryPhosphorus         ,
        "dietary_potassium"                   : HKQuantityTypeIdentifierDietaryPotassium          ,
        "dietary_protein"                     : HKQuantityTypeIdentifierDietaryProtein            ,
        "dietary_riboflavin"                  : HKQuantityTypeIdentifierDietaryRiboflavin         ,
        "dietary_selenium"                    : HKQuantityTypeIdentifierDietarySelenium           ,
        "dietary_sodium"                      : HKQuantityTypeIdentifierDietarySodium             ,
        "dietary_sugar"                       : HKQuantityTypeIdentifierDietarySugar              ,
        "dietary_thiamin"                     : HKQuantityTypeIdentifierDietaryThiamin            ,
        "dietary_vitamina"                    : HKQuantityTypeIdentifierDietaryVitaminA           ,
        "dietary_vitaminb12"                  : HKQuantityTypeIdentifierDietaryVitaminB12         ,
        "dietary_vitaminb6"                   : HKQuantityTypeIdentifierDietaryVitaminB6          ,
        "dietary_vitaminc"                    : HKQuantityTypeIdentifierDietaryVitaminC           ,
        "dietary_vitamind"                    : HKQuantityTypeIdentifierDietaryVitaminD           ,
        "dietary_vitamine"                    : HKQuantityTypeIdentifierDietaryVitaminE           ,
        "dietary_vitamink"                    : HKQuantityTypeIdentifierDietaryVitaminK           ,
        "dietary_water"                       : HKQuantityTypeIdentifierDietaryWater              ,
        "dietary_zinc"                        : HKQuantityTypeIdentifierDietaryZinc               ,
        "electrodermal_activity"              : HKQuantityTypeIdentifierElectrodermalActivity     ,
        "forced_expiratory_volume_one_second" : HKQuantityTypeIdentifierForcedExpiratoryVolume1   ,
        "forced_vital_capacity"               : HKQuantityTypeIdentifierForcedVitalCapacity       ,
        "heart_rate"                          : HKQuantityTypeIdentifierHeartRate                 ,
        "body_height"                         : HKQuantityTypeIdentifierHeight                    ,
        "inhaler_usage"                       : HKQuantityTypeIdentifierInhalerUsage              ,
        "lean_body_mass"                      : HKQuantityTypeIdentifierLeanBodyMass              ,
        "nike_fuel"                           : HKQuantityTypeIdentifierNikeFuel                  ,
        "number_of_times_fallen"              : HKQuantityTypeIdentifierNumberOfTimesFallen       ,
        "blood_oxygen_saturation"             : HKQuantityTypeIdentifierOxygenSaturation          ,
        "peak_expiratory_flow"                : HKQuantityTypeIdentifierPeakExpiratoryFlowRate    ,
        "peripheral_perfusion_index"          : HKQuantityTypeIdentifierPeripheralPerfusionIndex  ,
        "respiratory_rate"                    : HKQuantityTypeIdentifierRespiratoryRate           ,
        "uv_exposure"                         : HKQuantityTypeIdentifierUVExposure
    ]

    public let hkActivityToMCDB : [HKWorkoutActivityType: String] = [
        .AmericanFootball             : "american_football"               ,
        .Archery                      : "archery"                         ,
        .AustralianFootball           : "australian_football"             ,
        .Badminton                    : "badminton"                       ,
        .Baseball                     : "baseball"                        ,
        .Basketball                   : "basketball"                      ,
        .Bowling                      : "bowling"                         ,
        .Boxing                       : "boxing"                          ,
        .Climbing                     : "climbing"                        ,
        .Cricket                      : "cricket"                         ,
        .CrossTraining                : "cross_training"                  ,
        .Curling                      : "curling"                         ,
        .Cycling                      : "cycling"                         ,
        .Dance                        : "dance"                           ,
        .DanceInspiredTraining        : "dance_inspired_training"         ,
        .Elliptical                   : "elliptical"                      ,
        .EquestrianSports             : "equestrian_sports"               ,
        .Fencing                      : "fencing"                         ,
        .Fishing                      : "fishing"                         ,
        .FunctionalStrengthTraining   : "functional_strength_training"    ,
        .Golf                         : "golf"                            ,
        .Gymnastics                   : "gymnastics"                      ,
        .Handball                     : "handball"                        ,
        .Hiking                       : "hiking"                          ,
        .Hockey                       : "hockey"                          ,
        .Hunting                      : "hunting"                         ,
        .Lacrosse                     : "lacrosse"                        ,
        .MartialArts                  : "martial_arts"                    ,
        .MindAndBody                  : "mind_and_body"                   ,
        .MixedMetabolicCardioTraining : "mixed_metabolic_cardio_training" ,
        .PaddleSports                 : "paddle_sports"                   ,
        .Play                         : "play"                            ,
        .PreparationAndRecovery       : "preparation_and_recovery"        ,
        .Racquetball                  : "racquetball"                     ,
        .Rowing                       : "rowing"                          ,
        .Rugby                        : "rugby"                           ,
        .Running                      : "running"                         ,
        .Sailing                      : "sailing"                         ,
        .SkatingSports                : "skating_sports"                  ,
        .SnowSports                   : "snow_sports"                     ,
        .Soccer                       : "soccer"                          ,
        .Softball                     : "softball"                        ,
        .Squash                       : "squash"                          ,
        .StairClimbing                : "stair_climbing"                  ,
        .SurfingSports                : "surfing_sports"                  ,
        .Swimming                     : "swimming"                        ,
        .TableTennis                  : "table_tennis"                    ,
        .Tennis                       : "tennis"                          ,
        .TrackAndField                : "track_and_field"                 ,
        .TraditionalStrengthTraining  : "traditional_strength_training"   ,
        .Volleyball                   : "volleyball"                      ,
        .Walking                      : "walking"                         ,
        .WaterFitness                 : "water_fitness"                   ,
        .WaterPolo                    : "water_polo"                      ,
        .WaterSports                  : "water_sports"                    ,
        .Wrestling                    : "wrestling"                       ,
        .Yoga                         : "yoga"                            ,
        .Other                        : "other"
    ]
}